#!/bin/bash
# ---------------------------------------------------------------------------
# This script installs files and services specific to the project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-pvr
#
# ---------------------------------------------------------------------------

PACKAGES=""
PROJECT="pi-pvr"
CONFIG_FILES="/etc/pvrctl.conf /etc/pvrctl.rc /etc/wake-on-rtc.conf"

rand="$RANDOM"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

install_packages() {
  if [ -n "$PACKAGES" ] && check_packages $PACKAGES; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y --no-upgrade install $PACKAGES
  fi
}

# --- save configuration   --------------------------------------------------

save_config() {
  for f in $CONFIG_FILES; do
    if [ -f "$f" ]; then
      mv "$f" "$f.$rand"
    fi
  done
}

# --- restore configuration   -----------------------------------------------

restore_config() {
  for f in $CONFIG_FILES; do
    if [ -f "$f.$rand" ]; then
      mv "$f" "$f.new.$rand"
      mv "$f.$rand" "$f"
      echo -e "[INFO] new version of configuration file $f saved to: $f.new.$rand" 2>&1
    fi
  done
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1


  for f in `find $(dirname "$0")/../files/ -type f -not -name "*.pyc"`; do
    target="${f#*files}"
    target_dir="${target%/*}"
    [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
    cp "$f" "$target"
    chown root:root "$target"
  done

  chmod 755 "/usr/local/bin/pvrctl.py"
  chmod 755 /usr/local/bin/pvr_*.sh
}

# --- configure system   ----------------------------------------------------

configure_system() {
  # we add an additional dependency to wake-on-rtc.service
  [ -f /etc/systemd/system/wake-on-rtc.service ] && \
            sed -i -e "/After=/s/$/ tvheadend.service/" \
                                    /etc/systemd/system/wake-on-rtc.service
}

# --- activate service   ----------------------------------------------------

enable_services() {
  :
}

# --- main program   --------------------------------------------------------

install_packages
save_configuration
install_files
restore_configuration
configure_system
enable_services

echo "[INFO] installation completed"
